name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch (usually main)
  push:
    branches:
      - main # Or whichever branch you use as default

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest # Use the latest ubuntu runner
    env:
      HUGO_VERSION: 0.144.2 # Specify the Hugo version you are using locally (check with `hugo version`)
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch Hugo theme (if using submodules)

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Hugo
        env:
          # Set the base URL for the production build
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          # Make sure to set the baseURL in your hugo.toml correctly for GitHub Pages
          # Example: baseURL = "https://yourusername.github.io/your-repo-name/"
          # Or for user page: baseURL = "https://yourusername.github.io/"
        run: |
          hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
          # --gc: Garbage collect unused resources
          # --minify: Minify HTML, CSS, JS
          # --baseURL: Overrides the baseURL from config, using the one GitHub Pages expects

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'public' directory generated by Hugo
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Depends on the build job finishing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Official GitHub action